# Generated by Django 4.2.4 on 2023-08-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ficha', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('cupo', models.IntegerField()),
                ('duracionMeses', models.IntegerField()),
                ('jornada', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
    ]
