# Generated by Django 4.2.4 on 2023-08-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='programas_registrados',
            field=models.ManyToManyField(to='inscripciones.programa'),
        ),
    ]
